
- name: Add logstash repo
  copy:
    src=etc/yum.repos.d/logstash.repo
    dest=/etc/yum.repos.d/logstash.repo

- name: install logstash
  yum:
    name=logstash
    state=present

- name: Add logstash input config file
  copy:
    src=etc/logstash/conf.d/input.conf
    dest=/etc/logstash/conf.d/input.conf
  notify:
    - restart logstash

- name: Add logstash output config file
  copy:
    src=etc/logstash/conf.d/output.conf
    dest=/etc/logstash/conf.d/output.conf
  notify:
    - restart logstash

- name: start logstash
  service:
    name=logstash
    state=started
    enabled=yes
