---
- hosts: all
  sudo: true
  remote_user: vagrant
  roles:
    - common

- hosts: slaves
  sudo: true
  remote_user: vagrant
  roles:
    - slave

- hosts: masters
  sudo: true
  remote_user: vagrant
  roles:
    - master
