- name: stop firewalld service
  service:
    name=firewalld
    state=stopped
    enabled=no

- name: disable selinux
  selinux:
    state=disabled

- name: disable selinux now
  command: setenforce 0

- name: adding hosts file to make life easier
  copy:
    src=/etc/hosts
    dest=/etc/hosts
