- name: Install Mesosphere yum repo
  yum:
    name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state=present

- name: Install mesos package
  yum: 
    name={{ item }}
    state=present
  with_items:
    - mesos
    - marathon
    - mesosphere-zookeeper

- name: zookeeper ID
  template:
    src=var/lib/zookeeper/myid.j2
    dest=/var/lib/zookeeper/myid

- name: zookeeper config
  template:
    src=etc/zookeeper/conf/zoo.cfg.j2
    dest=/etc/zookeeper/conf/zoo.cfg

- name: start zookeeper service
  service:
    name=zookeeper
    state=started
    enabled=yes

- name: configure zk url
  template:
    src=etc/mesos/zk.j2
    dest=/etc/mesos/zk

- name: set hostname
  copy:
    src=etc/mesos-master/hostname
    dest=/etc/mesos-master/hostname

- name: set quorum
  copy:
    src=etc/mesos-master/quorum
    dest=/etc/mesos-master/quorum

- name: stop and disable mesos slave
  service:
    name=mesos-slave
    state=stopped
    enabled=no

- name: start mesos-master service
  service:
    name=mesos-master
    state=started
    enabled=yes

- name: start marathon service
  service:
    name=marathon
    state=started
    enabled=yes
