- name: Add Elasticsearch repo
  copy:
    src=etc/yum.repos.d/elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo

- name: install Elasticsearch
  yum:
    name=elasticsearch
    state=present

- name: elasticsearch config file
  template:
    src=etc/elasticsearch/elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- name: start elasticsearch
  service:
    name=elasticsearch
    state=started
    enabled=yes
